name: Deploy Astro Website

on:
  push:
    branches: [ main ]

  repository_dispatch:
    types: [ content_updated ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: main

      - name: Update Submodules
        run: |
          git submodule update --remote --recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete # 增量同步并删除服务器上多余的文件
          path: dist/
          remote_port: 202
          remote_path: /var/www/Blog
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          